const departments = [
    "Aerospace Engineering",
    "Biological Sciences and Bioengineering",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Cognitive Science",
    "Computer Science and Engineering",
    "Dean Of Academic Affairs",
    "Dean Of Research & Development", 
    "Dean Of Resource & Alumni",
    "Design",
    "Earth Science",
    "Economics",
    "Electrical Engineering",
    "Environmental Engineering and Management",
    "Humanities and Social Sciences",
    "Industrial and Management Engineering",
    "Laser Technology",
    "Materials Science Programme",
    "Materials Science and Engineering",
    "Mathematics",
    "Mathematics and Scientific Computing",
    "Mathematics and Statistics",
    "Mechanical Engineering",
    "Nuclear Engineering and Technology Programme",
    "Photonics Science and Engineering",
    "Physics",
    "Space Science and Astronomy",
    "Space, Planetary and Astronomical Sciences and Engineering",
    "Statistics",
    "Statistics and Data Science",
    "Sustainable Energy Engineering"
  ];

  export default departments;